#!/bin/bash

LONG_DATE=`date +%Y%m%d%H%M%S`

TOMCAT=tomcat9
TOMCAT_USER=tomcat
TOMCAT_HOME=/var/lib/${TOMCAT}
APACHE_CONF=/etc/apache2

systemctl stop ${TOMCAT}
/etc/init.d/apache2 stop


#SOURCE_DIR=/usr/share/portal
#rm -rf ${SOURCE_DIR}

rm -rf ${TOMCAT_HOME}/webapps/portal
rm -f ${TOMCAT_HOME}/webapps/portal*
rm -f ${TOMCAT_HOME}/conf/Catalina/localhost/portal.xml
rm -f ${TOMCAT_HOME}/conf/policy.d/56portal.policy
rm -f ${APACHE_CONF}/jk_mount/portal_jk.*

rm -rf /etc/dataone/portal

systemctl start ${TOMCAT}
/etc/init.d/apache2 start

## Update DateONE Version Info Doc
java -jar /usr/share/dataone-cn-version-tool/dataone-cn-version-tool.jar -F/usr/share/dataone-cn-version-tool/version-tool.properties -html > /var/www/cn-version.html

exit 0
